blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using tlsx
    url: https://github.com/projectdiscovery/tlsx/discussions/categories/q-a
    about: Ask a question or request support for using tlsx

  - name: Share idea / feature to discuss for tlsx
    url: https://github.com/projectdiscovery/tlsx/discussions/categories/ideas
    about: Share idea / feature to discuss for tlsx

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication