name: 🎉 Release Binary

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: projectdiscovery/actions/setup/go@v1

      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v4
        with:
          args: "release --clean"
          version: latest
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
